version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - boarding_network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_DATA: /var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: boarding_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - boarding_network

volumes:
  mysql_data:
  rabbitmq_data:

networks:
  boarding_network:
    driver: bridge
